=== KaragkounisL/University-WebSite/Website Files/files/students.dtd
<!ELEMENT students (student*)>
<!ELEMENT student (name, surname, semester, passed_subjects, average)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT passed_subjects (#PCDATA)>
<!ELEMENT average (#PCDATA)>

=== KaragkounisL/University-WebSite/Website Files/files/students3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
  <student>
    <name>Emily</name>
    <surname>Dunn</surname>
    <semester>2</semester>
    <passed_subjects>1</passed_subjects>
    <average>10</average>
  </student>
  <student>
    <name>Matilda</name>
    <surname>Hodges</surname>
    <semester>2</semester>
    <passed_subjects>2</passed_subjects>
    <average>7.5</average>
  </student>
  <student>
    <name>Alice</name>
    <surname>Kain</surname>
    <semester>2</semester>
    <passed_subjects>4</passed_subjects>
    <average>7.75</average>
  </student>
</students>
